#!/bin/bash

#  The prerm script may be called in the following ways:

#  prerm remove
#  old-prerm upgradenew-version
#  conflictor's-prerm remove in-favour package new-version
#  deconfigured's-prerm deconfigure in-favour package-being-installed version [removing conflicting-package version]
#  The package whose prerm is being called will be at least "Half-Installed".
#  All package dependencies will at least be "Half-Installed" and will have previously been configured and not removed.
#  If there was no error, all dependencies will at least be "Unpacked", but these actions may be called in various error
#  states where dependencies are only "Half-Installed" due to a partial upgrade.

#  new-prerm failed-upgrade old-version
#  Called during error handling when prerm upgrade fails. The new package will not yet be unpacked,
#  and all the same constraints as for preinst upgrade apply.

# немедленный выход, если выходное состояние команды ненулевое.
set -e

case "$1" in
    remove)
        echo "Prepare to remove packet @project-name@"
        service @project-name@ stop || true
    ;;
    upgrade)
        echo "Prepare to remove old version @project-name@ before upgrade"
        service @project-name@ stop || true
    ;;
    failed-upgrade|deconfigure)
        echo "Preprm execute with action ${1}"
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
